#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# SCRUM-20: puts the walking skeleton on one AWS EC2 host with HTTPS (ADR-0002).
# SCRUM-23: stage 10 lets GitHub Actions deploy a merge into main.
# Run it from anywhere: ./deploy/setup-aws.sh. Safe to run again; it finds what it already
# made (by the name "squadmeet") and remembers values in .env.aws (not in git).
# Needs: aws (CLI v2), gh, jq, curl, openssl, dig. Run it after the frontend image with
# Caddy is in GHCR (the SCRUM-20 PR is merged into dev).

cd "$(dirname "$0")/.."
ENV_FILE=".env.aws"
NAME="squadmeet"

die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"; exit 1; }

TOTAL_STAGES=10

banner "SquadMeet on AWS (SCRUM-20)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Tools and AWS login"
for tool in aws gh jq curl openssl dig base64; do
  command -v "$tool" >/dev/null 2>&1 || die "'$tool' is missing. Install it, then run this again."
done
ask AWS_REGION "AWS region (Enter for eu-central-1, Frankfurt):"
AWS_REGION="${AWS_REGION:-eu-central-1}"
write_env AWS_REGION "$AWS_REGION"
export AWS_REGION AWS_DEFAULT_REGION="$AWS_REGION"

if ! aws sts get-caller-identity >/dev/null 2>&1; then
  say "The AWS CLI is not logged in. A browser window opens for the AWS login."
  note "Use the same login as for the AWS console."
  aws login --region "$AWS_REGION" || die "AWS login failed. Run 'aws login' by hand, then run this again."
fi
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
CALLER=$(aws sts get-caller-identity --query Arn --output text)
say "Logged in as ${BOLD}${CALLER}${RESET}"
confirm "Is this the AWS account for the project?" || die "Log in to the right account ('aws login'), then run this again."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Budget alarm"
say "A monthly cost budget sends an email before the credit is used up."
note "It counts costs before credits, so you see real usage early."
if aws budgets describe-budget --region us-east-1 --account-id "$ACCOUNT_ID" \
     --budget-name "$NAME-monthly" >/dev/null 2>&1; then
  say "${GREEN}✓${RESET} Budget '$NAME-monthly' exists already."
else
  ask BUDGET_EMAIL "Email address for the alarm:"
  ask BUDGET_USD "Monthly limit in USD (Enter for 10):"
  BUDGET_USD="${BUDGET_USD:-10}"
  write_env BUDGET_EMAIL "$BUDGET_EMAIL"
  write_env BUDGET_USD "$BUDGET_USD"
  budget=$(jq -n --arg usd "$BUDGET_USD" --arg name "$NAME-monthly" '{
    BudgetName: $name, BudgetType: "COST", TimeUnit: "MONTHLY",
    BudgetLimit: {Amount: $usd, Unit: "USD"}, CostTypes: {IncludeCredit: false}}')
  alerts=$(jq -n --arg mail "$BUDGET_EMAIL" '[
    {Notification: {NotificationType: "ACTUAL", ComparisonOperator: "GREATER_THAN",
       Threshold: 50, ThresholdType: "PERCENTAGE"},
     Subscribers: [{SubscriptionType: "EMAIL", Address: $mail}]},
    {Notification: {NotificationType: "FORECASTED", ComparisonOperator: "GREATER_THAN",
       Threshold: 100, ThresholdType: "PERCENTAGE"},
     Subscribers: [{SubscriptionType: "EMAIL", Address: $mail}]}]')
  if aws budgets create-budget --region us-east-1 --account-id "$ACCOUNT_ID" \
       --budget "$budget" --notifications-with-subscribers "$alerts"; then
    say "${GREEN}✓${RESET} Budget '$NAME-monthly': $BUDGET_USD USD, email at 50 % used and at 100 % forecast."
  else
    warn "The CLI could not create the budget (an IAM user may have no billing access)."
    open_url "https://console.aws.amazon.com/billing/home#/budgets"
    step "Create budget → Use a template → Monthly cost budget."
    step "Name '$NAME-monthly', amount $BUDGET_USD USD, your email → Create budget."
    pause "Press Enter when the budget exists."
  fi
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Free subdomain (DuckDNS)"
say "DuckDNS gives a free name like squadmeet.duckdns.org. Stage 7 points it to the server."
open_url "https://www.duckdns.org"
step "Sign in at the top right (for example with GitHub)."
step "Type a name in the 'sub domain' field (for example 'squadmeet') → 'add domain'."
step "Your token is at the top of the page, next to 'token'."
ask DUCKDNS_SUBDOMAIN "Subdomain (only the name, without .duckdns.org):"
DUCKDNS_SUBDOMAIN="${DUCKDNS_SUBDOMAIN%.duckdns.org}"
[[ -n "$DUCKDNS_SUBDOMAIN" ]] || die "No subdomain given."
ask_secret DUCKDNS_TOKEN "Paste the DuckDNS token:"
[[ -n "$DUCKDNS_TOKEN" ]] || die "No token given."
DOMAIN="$DUCKDNS_SUBDOMAIN.duckdns.org"
write_env DUCKDNS_SUBDOMAIN "$DUCKDNS_SUBDOMAIN"
write_env DUCKDNS_TOKEN "$DUCKDNS_TOKEN"
write_env DOMAIN "$DOMAIN"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Secrets for the server (Parameter Store)"
say "The server pulls the private images from GHCR with a read-only GitHub token."
say "The token and the database password go to AWS SSM Parameter Store (encrypted)."
gh_login=$(gh api user --jq .login 2>/dev/null || true)
ask GHCR_USER "GitHub user name for the token (Enter for ${gh_login:-?}):"
GHCR_USER="${GHCR_USER:-$gh_login}"
[[ -n "$GHCR_USER" ]] || die "No GitHub user name given."
write_env GHCR_USER "$GHCR_USER"

replace_token=y
if aws ssm get-parameter --name "/$NAME/ghcr-token" >/dev/null 2>&1; then
  say "${GREEN}✓${RESET} A GHCR token is stored already."
  confirm "Replace it with a new token?" || replace_token=n
fi
if [[ "$replace_token" == y ]]; then
  open_url "https://github.com/settings/tokens/new?scopes=read:packages&description=$NAME-ec2-ghcr-pull"
  step "This is a classic token. The note and the scope 'read:packages' are filled in."
  step "Expiration: Custom → a date after the presentation (for example 2026-11-30)."
  step "Tick nothing else → 'Generate token' → copy it (starts with ghp_)."
  ask_secret GHCR_TOKEN "Paste the token:"
  [[ -n "$GHCR_TOKEN" ]] || die "No token given."
  say "Checking the token and the 'dev' frontend image in GHCR …"
  registry_token=$(curl -fsS -u "$GHCR_USER:$GHCR_TOKEN" \
    "https://ghcr.io/token?scope=repository:gitgitrice/$NAME-frontend:pull" | jq -r .token) \
    || die "GHCR did not accept the token. Check the user name and the read:packages scope."
  curl -fsS -o /dev/null -H "Authorization: Bearer $registry_token" \
    -H "Accept: application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.v2+json" \
    "https://ghcr.io/v2/gitgitrice/$NAME-frontend/manifests/dev" \
    || die "The token works, but the image $NAME-frontend:dev is not readable. Is the SCRUM-20 PR merged into dev?"
  aws ssm put-parameter --name "/$NAME/ghcr-token" --type SecureString \
    --value "$GHCR_TOKEN" --overwrite >/dev/null
  say "${GREEN}✓${RESET} stored /$NAME/ghcr-token"
fi
aws ssm put-parameter --name "/$NAME/ghcr-user" --type String --value "$GHCR_USER" --overwrite >/dev/null
say "${GREEN}✓${RESET} stored /$NAME/ghcr-user"
# Made once and never overwritten: the database volume keeps the first password.
if aws ssm get-parameter --name "/$NAME/postgres-password" >/dev/null 2>&1; then
  say "${GREEN}✓${RESET} /$NAME/postgres-password exists already (not changed)."
else
  aws ssm put-parameter --name "/$NAME/postgres-password" --type SecureString \
    --value "$(openssl rand -hex 24)" >/dev/null
  say "${GREEN}✓${RESET} stored a new random /$NAME/postgres-password"
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Firewall and server role"
say "This creates, if they do not exist yet:"
step "Security group '$NAME-web': only ports 80 and 443 open (no SSH)."
step "IAM role '$NAME-ec2': AWS SSM may run commands on the server; the server may read /$NAME/* in Parameter Store."
confirm "Create them now?" || die "Stopped. Nothing was created in this stage."

VPC_ID=$(aws ec2 describe-vpcs --filters Name=is-default,Values=true \
  --query 'Vpcs[0].VpcId' --output text)
if [[ "$VPC_ID" == "None" ]]; then
  # Some accounts (for example course accounts) have no default VPC in this region.
  warn "There is no default VPC in $AWS_REGION. A default VPC costs nothing."
  confirm "Create the default VPC now?" || die "Stopped. Create it later: VPC console → Actions → Create default VPC."
  VPC_ID=$(aws ec2 create-default-vpc --query Vpc.VpcId --output text)
  say "${GREEN}✓${RESET} Default VPC $VPC_ID"
fi

SG_ID=$(aws ec2 describe-security-groups \
  --filters Name=group-name,Values="$NAME-web" Name=vpc-id,Values="$VPC_ID" \
  --query 'SecurityGroups[0].GroupId' --output text)
if [[ "$SG_ID" == "None" ]]; then
  SG_ID=$(aws ec2 create-security-group --group-name "$NAME-web" --vpc-id "$VPC_ID" \
    --description "SquadMeet: HTTP and HTTPS only" --query GroupId --output text)
fi
for rule in tcp:80 tcp:443 udp:443; do
  # A rule that exists already gives an error; that is fine.
  aws ec2 authorize-security-group-ingress --group-id "$SG_ID" \
    --protocol "${rule%%:*}" --port "${rule##*:}" --cidr 0.0.0.0/0 >/dev/null 2>&1 || true
done
write_env SG_ID "$SG_ID"
say "Open ports of $SG_ID:"
aws ec2 describe-security-groups --group-ids "$SG_ID" \
  --query 'SecurityGroups[0].IpPermissions[].[IpProtocol,FromPort,IpRanges[0].CidrIp]' --output table

if ! aws iam get-role --role-name "$NAME-ec2" >/dev/null 2>&1; then
  aws iam create-role --role-name "$NAME-ec2" >/dev/null --assume-role-policy-document '{
    "Version": "2012-10-17",
    "Statement": [{"Effect": "Allow", "Principal": {"Service": "ec2.amazonaws.com"},
                   "Action": "sts:AssumeRole"}]}'
fi
aws iam attach-role-policy --role-name "$NAME-ec2" \
  --policy-arn arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
aws iam put-role-policy --role-name "$NAME-ec2" --policy-name "$NAME-read-parameters" \
  --policy-document "$(jq -n --arg arn "arn:aws:ssm:$AWS_REGION:$ACCOUNT_ID:parameter/$NAME/*" '{
    Version: "2012-10-17",
    Statement: [{Effect: "Allow", Action: ["ssm:GetParameter"], Resource: $arn}]}')"
if ! aws iam get-instance-profile --instance-profile-name "$NAME-ec2" >/dev/null 2>&1; then
  aws iam create-instance-profile --instance-profile-name "$NAME-ec2" >/dev/null
  aws iam add-role-to-instance-profile --instance-profile-name "$NAME-ec2" --role-name "$NAME-ec2"
fi
say "${GREEN}✓${RESET} Role and instance profile '$NAME-ec2' are ready."
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "EC2 server and fixed IP"
say "This starts, if it does not exist yet:"
step "EC2 't2.micro' (Free Tier in this account) with Amazon Linux 2023, 20 GB disk, Docker and a 2 GB swap file."
step "An Elastic IP (fixed address, about 3.60 USD a month from the credit)."
note "CPU credits are 'standard', so a busy CPU slows down instead of costing extra."
confirm "Start the server now?" || die "Stopped. No server was started."

INSTANCE_ID=$(aws ec2 describe-instances \
  --filters Name=tag:Name,Values="$NAME" Name=instance-state-name,Values=pending,running,stopping,stopped \
  --query 'Reservations[0].Instances[0].InstanceId' --output text)
if [[ "$INSTANCE_ID" == "None" ]]; then
  AMI_ID=$(aws ssm get-parameter \
    --name /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64 \
    --query Parameter.Value --output text)
  # A new instance profile takes a few seconds before EC2 can use it.
  for _ in 1 2 3 4 5 6; do
    INSTANCE_ID=$(aws ec2 run-instances --image-id "$AMI_ID" --instance-type t2.micro \
      --security-group-ids "$SG_ID" --iam-instance-profile Name="$NAME-ec2" \
      --credit-specification CpuCredits=standard \
      --metadata-options HttpTokens=required,HttpEndpoint=enabled \
      --block-device-mappings '[{"DeviceName":"/dev/xvda","Ebs":{"VolumeSize":20,"VolumeType":"gp3"}}]' \
      --user-data file://deploy/ec2-user-data.sh \
      --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$NAME}]" \
      --query 'Instances[0].InstanceId' --output text 2>/dev/null) && break
    note "EC2 does not see the new role yet; trying again in 10 s …"
    sleep 10
  done
  [[ "$INSTANCE_ID" == i-* ]] || die "Could not start the instance. Run this again; it continues here."
  say "Started $INSTANCE_ID"
elif [[ "$(aws ec2 describe-instances --instance-ids "$INSTANCE_ID" \
          --query 'Reservations[0].Instances[0].State.Name' --output text)" == stopped ]]; then
  aws ec2 start-instances --instance-ids "$INSTANCE_ID" >/dev/null
fi
say "Waiting until $INSTANCE_ID runs …"
aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
write_env INSTANCE_ID "$INSTANCE_ID"

ALLOCATION_ID=$(aws ec2 describe-addresses --filters Name=tag:Name,Values="$NAME" \
  --query 'Addresses[0].AllocationId' --output text)
if [[ "$ALLOCATION_ID" == "None" ]]; then
  ALLOCATION_ID=$(aws ec2 allocate-address --domain vpc \
    --tag-specifications "ResourceType=elastic-ip,Tags=[{Key=Name,Value=$NAME}]" \
    --query AllocationId --output text)
fi
aws ec2 associate-address --instance-id "$INSTANCE_ID" --allocation-id "$ALLOCATION_ID" >/dev/null
ELASTIC_IP=$(aws ec2 describe-addresses --allocation-ids "$ALLOCATION_ID" \
  --query 'Addresses[0].PublicIp' --output text)
write_env ELASTIC_IP "$ELASTIC_IP"
say "${GREEN}✓${RESET} $INSTANCE_ID runs with the fixed IP $ELASTIC_IP"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Point $DOMAIN to $ELASTIC_IP"
answer=$(curl -fsS "https://www.duckdns.org/update?domains=$DUCKDNS_SUBDOMAIN&token=$DUCKDNS_TOKEN&ip=$ELASTIC_IP" || true)
[[ "$answer" == OK ]] || die "DuckDNS answered '$answer'. Check the subdomain and the token (run this again, stage 3)."
say "${GREEN}✓${RESET} DuckDNS has the new IP."
say "Waiting until the name resolves (usually under a minute) …"
for _ in $(seq 1 30); do
  [[ "$(dig +short "$DOMAIN" @1.1.1.1 | tail -n1)" == "$ELASTIC_IP" ]] && break
  sleep 10
done
[[ "$(dig +short "$DOMAIN" @1.1.1.1 | tail -n1)" == "$ELASTIC_IP" ]] \
  || die "$DOMAIN does not point to $ELASTIC_IP after 5 minutes. Run this again later."
say "${GREEN}✓${RESET} $DOMAIN → $ELASTIC_IP"
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Start the app on the server (through AWS SSM)"
say "Waiting until the server reports to AWS SSM (the first boot takes a few minutes) …"
for _ in $(seq 1 60); do
  [[ "$(aws ssm describe-instance-information \
        --filters Key=InstanceIds,Values="$INSTANCE_ID" \
        --query 'InstanceInformationList[0].PingStatus' --output text)" == Online ]] && break
  sleep 10
done
[[ "$(aws ssm describe-instance-information --filters Key=InstanceIds,Values="$INSTANCE_ID" \
      --query 'InstanceInformationList[0].PingStatus' --output text)" == Online ]] \
  || die "The server does not report to SSM after 10 minutes. Look at EC2 → Instance → Actions → Monitor → Get system log."

# Same path as the automatic deploy (SCRUM-23). The tag "main" exists after the first
# merge into main; before that, run the wizard with DEPLOY_TAG=dev.
DEPLOY_TAG="${DEPLOY_TAG:-main}"
say "Sending compose.yml and host-deploy.sh, then: pull the '$DEPLOY_TAG' images and start …"
AWS_REGION="$AWS_REGION" EC2_INSTANCE_ID="$INSTANCE_ID" APP_DOMAIN="$DOMAIN" \
  deploy/deploy.sh "$DEPLOY_TAG" || die "The deploy on the server failed (output above)."
say "${GREEN}✓${RESET} The stack runs on the server."
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Check https://$DOMAIN"
say "Caddy gets the Let's Encrypt certificate on the first request (up to a minute) …"
healthy=n
for _ in $(seq 1 30); do
  # curl checks the certificate: an invalid one fails here.
  if curl -fsS "https://$DOMAIN/api/health" 2>/dev/null | grep -q '"ok"'; then healthy=y; break; fi
  sleep 10
done
[[ "$healthy" == y ]] || die "https://$DOMAIN/api/health does not answer. Logs: see deploy/README.md → Troubleshooting."
say "${GREEN}✓${RESET} https://$DOMAIN/api/health answers, the certificate is valid."
# The bbox (Leipzig) is required since SCRUM-21; the API before SCRUM-21 ignores it.
say "Places in Leipzig: $(curl -fsS "https://$DOMAIN/api/places?bbox=12.2,51.2,12.6,51.5" | jq length)"
open_url "https://$DOMAIN"
step "You should see the map with Places in Leipzig."
confirm "Do you see the map with the Place?" || warn "Not as expected. See deploy/README.md → Troubleshooting."

pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Automatic deploy from GitHub (SCRUM-23)"
say "A merge into main deploys through AWS SSM. GitHub logs in to AWS with OIDC, so no AWS"
say "keys are stored in GitHub. Only runs on main of this repo may use the deploy role."
step "Creates the OIDC provider for GitHub and the IAM role '$NAME-github-deploy'."
confirm "Create them now?" || die "Stopped. Nothing was created in this stage."
deploy/setup-github-deploy.sh "$INSTANCE_ID" || die "The deploy role setup failed (output above)."
say "The deploy job reads these GitHub variables (not secret):"
set_var AWS_REGION "$AWS_REGION"
set_var EC2_INSTANCE_ID "$INSTANCE_ID"
set_var APP_DOMAIN "$DOMAIN"
pause

finish
say "App:       https://$DOMAIN"
say "Server:    $INSTANCE_ID ($ELASTIC_IP, $AWS_REGION)"
say "Shell:     aws ssm start-session --target $INSTANCE_ID   (needs the Session Manager plugin)"
printf '\n'
