#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# Turnstile keys for production (SCRUM-27): makes the Cloudflare Turnstile widget and stores
# its two keys in AWS SSM Parameter Store, where deploy/host-deploy.sh reads them.
# Nothing goes to .env or GitHub: local development and CI use Cloudflare's test keys.
#
# Usage: deploy/setup-turnstile.sh   (needs the AWS CLI, curl and jq)
# Run it again to replace the keys, for example at the handover to Stefan (SCRUM-48).

TOTAL_STAGES=5
NAME=squadmeet
AWS_REGION="${AWS_REGION:-eu-central-1}"
DOMAIN="${DOMAIN:-$NAME.duckdns.org}"
SITE_PARAM="/$NAME/turnstile-site-key"
SECRET_PARAM="/$NAME/turnstile-secret-key"
SITEVERIFY_URL="https://challenges.cloudflare.com/turnstile/v0/siteverify"

die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"; exit 1; }
ssm() { aws ssm --region "$AWS_REGION" "$@"; }

for tool in aws curl jq; do
  command -v "$tool" >/dev/null 2>&1 || die "'$tool' is missing. Install it, then run this again."
done

banner "Squadmeet — Turnstile keys (captcha, SCRUM-27)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "AWS login"
say "The keys go to AWS SSM Parameter Store in the project's AWS account ($AWS_REGION)."
if ! aws sts get-caller-identity >/dev/null 2>&1; then
  say "You are not logged in to AWS. A browser opens for the login."
  aws login --region "$AWS_REGION" || die "AWS login failed. Run 'aws login' by hand, then run this again."
fi
say "Logged in as: $(aws sts get-caller-identity --query Arn --output text)"
say "Account:      $(aws sts get-caller-identity --query Account --output text)"
confirm "Is this the AWS account that runs $DOMAIN?" \
  || die "Log in to the right account ('aws login'), then run this again."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Keys that exist already"
if ssm get-parameter --name "$SECRET_PARAM" >/dev/null 2>&1; then
  say "Keys are stored already."
  say "Site key now: $(ssm get-parameter --name "$SITE_PARAM" --query Parameter.Value --output text 2>/dev/null || echo '(missing)')"
  warn "New keys replace them. The old widget keeps working until you delete it in Cloudflare."
  confirm "Replace them with the keys of a new widget?" || { say "Nothing changed."; exit 0; }
else
  say "No Turnstile keys are stored yet. The next deploy from main needs them:"
  note "without them, deploy/host-deploy.sh stops."
  pause
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare — make the widget"
say "Log in to the Cloudflare account that owns the hosting."
note "Until the handover to Stefan (SCRUM-48), that is Steven's account."
open_url "https://dash.cloudflare.com/?to=/:account/turnstile"
step "Left menu: Turnstile (if you do not see it, search for 'Turnstile')."
step "Click 'Add widget'."
step "Widget name: $NAME"
step "Hostnames: add $DOMAIN (only this one; local development uses test keys)."
step "Widget mode: Managed. Pre-clearance: No."
step "Click 'Create'. Cloudflare shows the Site Key and the Secret Key."
ask TURNSTILE_SITE_KEY "Paste the Site Key:"
[[ -n "$TURNSTILE_SITE_KEY" ]] || die "No site key given."
[[ "$TURNSTILE_SITE_KEY" == 0x* ]] \
  || warn "A site key usually starts with 0x. Check that you did not copy the secret key."
ask_secret TURNSTILE_SECRET_KEY "Paste the Secret Key (hidden):"
[[ -n "$TURNSTILE_SECRET_KEY" ]] || die "No secret key given."
[[ "$TURNSTILE_SECRET_KEY" != "$TURNSTILE_SITE_KEY" ]] || die "Both keys are the same. Copy the Secret Key."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Check the secret key with Cloudflare"
say "One test request with a fake token. A real secret key gets 'invalid token';"
say "a wrong secret key gets 'invalid secret'."
# The secret goes to curl through stdin, so it is not in the process list. No -f: Cloudflare
# answers a wrong secret with HTTP 400, and the body says why.
answer=$(printf '%s' "$TURNSTILE_SECRET_KEY" | curl -sS "$SITEVERIFY_URL" \
  --data-urlencode "secret@-" --data "response=wizard-check") \
  || die "Cloudflare did not answer. Check the internet connection, then run this again."
codes=$(jq -r '."error-codes" // [] | join(",")' <<<"$answer" 2>/dev/null) || codes=""
if [[ "$(jq -r '.success' <<<"$answer" 2>/dev/null)" == true ]]; then
  # Only a test key accepts a fake token.
  die "This is a Cloudflare test key, which accepts every token. Copy the widget's real Secret Key."
elif [[ "$codes" == *invalid-input-secret* ]]; then
  die "Cloudflare does not know this secret key. Copy it again from the widget (stage 3)."
elif [[ "$codes" == *invalid-input-response* ]]; then
  say "${GREEN}✓${RESET} Cloudflare knows the secret key."
else
  warn "Unexpected answer from Cloudflare: ${codes:-$answer}"
  confirm "Store the keys anyway?" || die "Nothing stored."
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Store the keys in Parameter Store"
step "$SITE_PARAM   (String; public, the widget in the browser shows it)"
step "$SECRET_PARAM (SecureString; encrypted)"
confirm "Store both keys now (replaces old values)?" || die "Nothing stored."
ssm put-parameter --name "$SITE_PARAM" --type String \
  --value "$TURNSTILE_SITE_KEY" --overwrite >/dev/null
ssm put-parameter --name "$SECRET_PARAM" --type SecureString \
  --value "$TURNSTILE_SECRET_KEY" --overwrite >/dev/null
stored=$(ssm get-parameter --name "$SITE_PARAM" --query Parameter.Value --output text)
[[ "$stored" == "$TURNSTILE_SITE_KEY" ]] || die "The site key in Parameter Store does not match. Run this again."
say "${GREEN}✓${RESET} stored $SITE_PARAM and $SECRET_PARAM"
unset TURNSTILE_SECRET_KEY
pause

finish
note "Turnstile widget '$NAME' for $DOMAIN; keys in $SITE_PARAM and $SECRET_PARAM."
note "The keys take effect at the next deploy (a merge into main, or deploy/deploy.sh <tag>)."
note "Check after the deploy: the register form on https://$DOMAIN shows the widget,"
note "and registration works."
printf '\n'
